name: Generate SVG Assets (Collect Logs)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  image-gen-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup console2svg
        uses: ./

      - name: Install dependencies
        run: |
          sudo npm install -g oh-my-logo
          sudo apt-get install -y sl htop vim

      - name: Generate images
        run: bash scripts/image-gen.sh

      - name: Generated images upload
        uses: actions/upload-artifact@v6
        with:
          name: generate-svg-images
          path: assets/

      - name: Log Artifacts upload
        uses: actions/upload-artifact@v6
        with:
          name: generate-svg-logs
          path: logs/
