name: Generate Assets (Collect Logs)

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'scripts/image-gen.sh'
  #     - 'src/ConsoleToSvg/**'
  #     - 'assets/*.json'
  #     - 'action.yml'
  #     - '.github/workflows/image-gen.yaml'

permissions:
  contents: write

jobs:
  image-gen-logs:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      COLORTERM: truecolor
      FORCE_COLOR: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup console2svg
        uses: ./

      - name: Install dependencies
        run: |
          sudo npm install -g oh-my-logo
          sudo apt-get install -y sl nyancat vim

      - name: Generate images
        run: bash scripts/image-gen.sh

      - name: Log Artifacts upload
        uses: actions/upload-artifact@v6
        with:
          name: generate-svg-logs
          path: logs/
